# https://github.com/prometheus-community/ansible
- hosts: proxmox_hosts
  gather_facts: true

  vars:
    node_exporter_version: "1.8.1" # https://github.com/prometheus/node_exporter


  roles:
    - role: prometheus.prometheus.node_exporter
