---
# Required vars:
# vms - List of data to create new VMs { name, ip_address, hdd_size, destination_node }
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Add VM hostname to inventory
      ansible.builtin.add_host:
        hostname: '{{ vm_dns_name }}'
        groups: proxmox_vm
        vm_name: "{{ item.name }}"
      vars:
        vm_name: "{{ item.name }}" # Needed to generate vm_dns_name
      loop: '{{ vms }}'
      changed_when: false

    - name: Clear host from known_host
      ansible.builtin.command:
        cmd: ssh-keygen -R "{{ item.name }}"
      loop: '{{ vms }}'

- hosts: proxmox_vm
  gather_facts: false

  tasks:
    - name: Ping to refresh host key
      ansible.builtin.ping:
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new' # Host is new. Auto-accept key

- hosts: proxmox_hosts
  gather_facts: false

  tasks:
    - name: Clear host from known_host
      ansible.builtin.command:
        cmd: ssh-keygen -R "{{ inventory_hostname }}"
      delegate_to: localhost

    - name: Ping to refresh host key
      ansible.builtin.ping:
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new' # Host is new. Auto-accept key
