---
collections:
  - name: https://github.com/ansible-collections/community.general.git # community.general
    version: main # 7.1.0
    type: git
  - name: https://github.com/prometheus-community/ansible.git # prometheus.prometheus
    version: main # 0.16.3
    type: git
  - name: community.proxmox
    version: 1.0.1

roles:
  - src: xanmanning.k3s
    version: "v3.4.4"
