- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Add VM hostname to inventory
      ansible.builtin.add_host:
        hostname: '{{ vm_dns_name }}'
        groups: proxmox_vm
        vm_name: "{{ item.name }}"
      vars:
        vm_name: "{{ item.name }}" # Needed to generate vm_dns_name
      loop: '{{ vms }}'
      changed_when: false

- hosts: proxmox_vm
  gather_facts: false

  tasks:
    - name: Ping to refresh host key
      ansible.builtin.command:
        cmd: "{{ item }}"
      become: true
      loop:
        - sed -ie 's/.*\(search\|drewburr\).*//' /etc/netplan/50-cloud-init.yaml
        - netplan generate
        - netplan apply
