- hosts: all
  gather_facts: false

  vars:
    hostname_map:
      192.168.4.70: worker01.drewburr.com
      192.168.4.71: controlplane01.drewburr.com
      192.168.4.72: etcd01.drewburr.com
    ansible_python_interpreter: auto

  tasks:
    - name: Debug hostname
      ansible.builtin.debug:
        msg: hostnamectl set-hostname {{ hostname_map[inventory_hostname] }}
      become: true

    - name: Set hostname
      ansible.builtin.command:
        cmd: hostnamectl set-hostname {{ hostname_map[inventory_hostname] }}
      become: true
