- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Add VM hostname to inventory
    ansible.builtin.add_host:
      hostname: "{{ vm_dns_name }}"
      groups: vms
      vm_name: "{{ item.name }}"
    vars:
      vm_name: "{{ item.name }}" # Needed to generate vm_dns_name
    loop: "{{ vms }}"
    changed_when: false

- hosts: vms
  gather_facts: false

  tasks:
    - name: Clear host from known_hosts
      ansible.builtin.command:
        cmd: ssh-keygen -R "{{ vm_dns_name }}"
      vars:
        ansible_connection: local
      throttle: 1 # Avoid stepping on eachother

    - name: Add host to known_hosts
      ansible.builtin.ping:
      vars:
        ansible_ssh_user: ubuntu
        ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new" # Host is new. Auto-accept key
