---
pihole:
  hosts:
    pihole.drewburr.com:

proxmox:
  hosts:
    localhost:

proxmox_hosts:
  hosts:
    pve01.drewburr.com:
    pve02.drewburr.com:
    pve03.drewburr.com:
    pve04.drewburr.com:
    pve05.drewburr.com:

node_exporter_vms:
  hosts:
    storage01.drewburr.com:

node_exporter_hosts:
  children:
    proxmox_hosts:
    node_exporter_vms:
  hosts:
    zbackup.drewburr.com:
